(* ::Package:: *)

 


(* ::Section:: *)
(*QGInsertionRule*)


(* ::Text:: *)
(*`QGInsertionRule["names"]` is a set of replacement rules for inserting explicit vertices, propagators and polarization vectors into the amplitudes generated by QGRAF. These rules are loaded via QGLoadInsertions. Running `QGInsertionRule[]` returns a list of the already loaded sets of rules.*)


(* ::Subsection:: *)
(*See also*)


(* ::Text:: *)
(*[Overview](Extra/FeynHelpers.md).*)


(* ::Subsection:: *)
(*Examples*)
