(* ::Package:: *)

 


(* ::Section:: *)
(*FSALoadNumericalResults*)


(* ::Text:: *)
(*`FSALoadNumericalResults[files]` is a simple function that loads numerical results generated by the FIESTA script created via `FSAPrepareSDEvaluate`   into Mathematica. The argument `files` is the output of `FSAPrepareSDEvaluate` that contains the full paths to `FIESTAScript.m` and the output file.*)


(* ::Text:: *)
(*The option`Chop` (set to `10^(-10)` by default) tells the function to remove numerical artefacts.*)


(* ::Subsection:: *)
(*See also*)


(* ::Text:: *)
(*[Overview](Extra/FeynHelpers.md), [PSDCreatePythonScripts](PSDCreatePythonScripts.md).*)


(* ::Subsection:: *)
(*Examples*)


files={
FileNameJoin[{$FeynHelpersDirectory,"Documentation","Examples","FIESTA","prop1LX11","FIESTAScript.m"}],
FileNameJoin[{"numres_1._1._1._fiesta.m"}]};


FSALoadNumericalResults[files]
