(* ::Package:: *)

 


(* ::Section:: *)
(*FIREStartFile*)


(* ::Text:: *)
(*`FIREStartFile` is an option for `FIREBurn`. It specifies, where the start file for FIRE (the one generated by `SaveStart[]`) will be saved. The default location is the `Database` folder inside `$FeynCalcDirectory`.*)


(* ::Subsection:: *)
(*See also*)


(* ::Text:: *)
(*[Overview](Extra/FeynHelpers.md), [FIREBurn](FIREBurn.md).*)


(* ::Subsection:: *)
(*Examples*)
