(* ::Package:: *)

 


(* ::Section:: *)
(*QGTZFCreateTeXFiles*)


(* ::Text:: *)
(*`QGTZFCreateTeXFiles[input_]` processes the T EX representation of Feynman diagrams generated by QGRAF in the TikZ-Feynman format. The input file is the path to the temporary diagrams file generated by QGCreateAmp.*)


(* ::Text:: *)
(*The function can be also invoked via `QGTZFCreateTeXFiles[qgOutput]` where `qgOutput` is the output of `QGCreateAmp`.*)


(* ::Text:: *)
(*Notice that to complete the creation of T EX files it is also necessary to provide a file that contains stylings for the involved fields defined up via `tikzset` and `tikzfeynmanset`. By default the function assumes that this file is called `tikz-styles.tex` and is located in the same directory as the input file. The full path to the styling file can be provided via the option `QGDiagramStyle`.*)


(* ::Text:: *)
(*The styling file contains stylings for the involved fields defined up via `tikzset` and `tikzfeynmanset`. This file can be generated in advance using `QGTZFCreateFieldStyles` in a semi-automatic fashion.*)


(* ::Text:: *)
(*The resulting T EX code is saved to the same directory as the input file.  When the option `Split` is set to `False` (default), all diagrams are put into a single tex file called  `diagrams.tex`. Compiling this file with `lualatex` can take some time,  which is why this approach is recommended only for a small $\mathcal{O}(10)$ number of diagrams. The name of the output file can be changed using the option `QGOutputDiagrams`. By default the alignment is to put 6 diagrams in one row. To change this number use the option `Alignment`.*)


(* ::Text:: *)
(*Setting the option `Split` to `True` will put each diagram into a single file. The function will also copy two shell scripts (specified via the option `CopyFile`) into the same directory which will automatize the process of compiling the source files and gluing them together. This requires the programs `GNU parallel` and `pdfunite`.*)


(* ::Subsection:: *)
(*See also*)


(* ::Text:: *)
(*[Overview](Extra/FeynHelpers.md), [QGConvertToFC](QGConvertToFC.md), [QGCreateAmp](QGCreateAmp.md), [QGTZFCreateFieldStyles](QGTZFCreateFieldStyles.md).*)


(* ::Subsection:: *)
(*Examples*)
