(* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ *)

(* :Title: FSALoadNumericalResults									*)

(*
	This software is covered by the GNU General Public License 3.
	Copyright (C) 2021-2024 Vladyslav Shtabovenko
*)

(* :Summary: 	Generates input for LoopIntegralFromPropagators				*)

(* ------------------------------------------------------------------------ *)

FSALoadNumericalResults::usage=
"FSALoadNumericalResults[files] is a simple function that loads numerical
results generated by the FIESTA script created via FSAPrepareSDEvaluate   into
Mathematica. The argument files is the output of FSAPrepareSDEvaluate that
contains the full paths to FIESTAScript.m and the output file.

The optionChop (set to 10^(-10) by default) tells the function to remove
numerical artefacts.";

FSALoadNumericalResults::failmsg =
"Error! FSALoadNumericalResults has encountered a fatal problem and must abort the computation. \
The problem reads: `1`"

Begin["`Package`"]
End[]

Begin["`FSALoadNumericalResults`Private`"]

pslnrVerbose::usage="";

Options[FSALoadNumericalResults] = {
	Chop									-> 10^(-10),
	FCVerbose								-> False
};

FSALoadNumericalResults[files:{{_String, _String}..}, opt:OptionsPattern[]] :=
	FSALoadNumericalResults[#, opt]&/@files;

FSALoadNumericalResults[{script_String, resFileName_String}, OptionsPattern[]] :=
	Block[{ dir, res, optChop, optN, resFile},

		optChop								= OptionValue[Chop];


		If[	OptionValue[FCVerbose]===False,
			pslnrVerbose=$VeryVerbose,
			If[	MatchQ[OptionValue[FCVerbose], _Integer],
				pslnrVerbose=OptionValue[FCVerbose]
			];
		];

		resFile = FileNameJoin[{DirectoryName[script],resFileName}];

		If[	!FileExistsQ[resFile],
			Message[FSALoadNumericalResults::failmsg,"The file " <> resFile <> "does not exist."];
			Abort[]
		];

		res = Get[resFile];

		If[optChop=!=False,
			res = Chop[res,optChop]
		];

		Return[res];

	];

End[]
